// -------------------------------------------------------------
// 
// File Name: hdlsrc\NexusA7MLmodel\ML_Regression.v
// Created: 2024-07-25 13:53:39
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: ML_Regression
// Source Path: NexusA7MLmodel/ML_Regression
// Hierarchy Level: 0
// Model version: 1.16
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ML_Regression
          (x1,
           x2,
           x3,
           x4,
           x5,
           x6,
           x7,
           ypred);


  input   signed [9:0] x1;  // sfix10
  input   signed [7:0] x2;  // int8
  input   signed [3:0] x3;  // sfix4
  input   signed [8:0] x4;  // sfix9_En5
  input   signed [8:0] x5;  // sfix9_En5
  input   signed [14:0] x6;  // sfix15_En10
  input   signed [1:0] x7;  // sfix2
  output  [15:0] ypred;  // ufix16_En16


  wire signed [15:0] Offset_out1;  // sfix16_En14
  wire signed [19:0] Gain_out1;  // sfix20_En18
  wire signed [31:0] Add_stage2_add_cast;  // sfix32_En27
  wire signed [31:0] Add_stage2_add_cast_1;  // sfix32_En27
  wire signed [31:0] Add_stage2_add_temp;  // sfix32_En27
  wire signed [20:0] Add_op_stage1;  // sfix21_En18
  wire signed [15:0] Gain1_out1;  // sfix16_En15
  wire signed [31:0] Add_stage3_add_cast;  // sfix32_En27
  wire signed [31:0] Add_stage3_add_cast_1;  // sfix32_En27
  wire signed [31:0] Add_stage3_add_temp;  // sfix32_En27
  wire signed [21:0] Add_op_stage2;  // sfix22_En18
  wire signed [7:0] Gain2_out1;  // sfix8_En10
  wire signed [31:0] Add_stage4_add_cast;  // sfix32_En27
  wire signed [31:0] Add_stage4_add_cast_1;  // sfix32_En27
  wire signed [31:0] Add_stage4_add_temp;  // sfix32_En27
  wire signed [22:0] Add_op_stage3;  // sfix23_En18
  wire signed [17:0] Gain3_out1;  // sfix18_En24
  wire signed [31:0] Add_stage5_add_cast;  // sfix32_En27
  wire signed [31:0] Add_stage5_add_cast_1;  // sfix32_En27
  wire signed [31:0] Add_stage5_add_temp;  // sfix32_En27
  wire signed [29:0] Add_op_stage4;  // sfix30_En24
  wire signed [17:0] Gain4_out1;  // sfix18_En18
  wire signed [31:0] Add_stage6_add_cast;  // sfix32_En27
  wire signed [31:0] Add_stage6_add_cast_1;  // sfix32_En27
  wire signed [31:0] Add_stage6_add_temp;  // sfix32_En27
  wire signed [30:0] Add_op_stage5;  // sfix31_En24
  wire signed [29:0] Gain5_out1;  // sfix30_En27
  wire signed [31:0] Add_stage7_add_cast;  // sfix32_En27
  wire signed [31:0] Add_stage7_add_cast_1;  // sfix32_En27
  wire signed [31:0] Add_stage7_add_temp;  // sfix32_En27
  wire signed [34:0] Add_op_stage6;  // sfix35_En27
  wire signed [3:0] Gain6_out1;  // sfix4_En7
  wire signed [31:0] Add_stage8_add_cast;  // sfix32_En27
  wire signed [31:0] Add_stage8_add_cast_1;  // sfix32_En27
  wire signed [31:0] Add_stage8_add_temp;  // sfix32_En27
  wire [15:0] Add_out1;  // ufix16_En16


  assign Offset_out1 = 16'sb1010110011000110;


  assign Gain_out1 = 10'sb0111011011 * x1;


  assign Add_stage2_add_cast = {{3{Offset_out1[15]}}, {Offset_out1, 13'b0000000000000}};
  assign Add_stage2_add_cast_1 = {{3{Gain_out1[19]}}, {Gain_out1, 9'b000000000}};
  assign Add_stage2_add_temp = Add_stage2_add_cast + Add_stage2_add_cast_1;
  assign Add_op_stage1 = Add_stage2_add_temp[29:9];



  assign Gain1_out1 = 8'sb01110100 * x2;


  assign Add_stage3_add_cast = {{2{Add_op_stage1[20]}}, {Add_op_stage1, 9'b000000000}};
  assign Add_stage3_add_cast_1 = {{4{Gain1_out1[15]}}, {Gain1_out1, 12'b000000000000}};
  assign Add_stage3_add_temp = Add_stage3_add_cast + Add_stage3_add_cast_1;
  assign Add_op_stage2 = Add_stage3_add_temp[30:9];



  assign Gain2_out1 = 4'sb0111 * x3;


  assign Add_stage4_add_cast = {Add_op_stage2[21], {Add_op_stage2, 9'b000000000}};
  assign Add_stage4_add_cast_1 = {{7{Gain2_out1[7]}}, {Gain2_out1, 17'b00000000000000000}};
  assign Add_stage4_add_temp = Add_stage4_add_cast + Add_stage4_add_cast_1;
  assign Add_op_stage3 = Add_stage4_add_temp[31:9];



  assign Gain3_out1 = 9'sb100111000 * x4;


  assign Add_stage5_add_cast = {Add_op_stage3, 9'b000000000};
  assign Add_stage5_add_cast_1 = {{11{Gain3_out1[17]}}, {Gain3_out1, 3'b000}};
  assign Add_stage5_add_temp = Add_stage5_add_cast + Add_stage5_add_cast_1;
  assign Add_op_stage4 = {Add_stage5_add_temp[31], Add_stage5_add_temp[31:3]};



  assign Gain4_out1 = 9'sb010100010 * x5;


  assign Add_stage6_add_cast = {Add_op_stage4[28:0], 3'b000};
  assign Add_stage6_add_cast_1 = {{5{Gain4_out1[17]}}, {Gain4_out1, 9'b000000000}};
  assign Add_stage6_add_temp = Add_stage6_add_cast + Add_stage6_add_cast_1;
  assign Add_op_stage5 = {{2{Add_stage6_add_temp[31]}}, Add_stage6_add_temp[31:3]};



  assign Gain5_out1 = 15'sb011101000110011 * x6;


  assign Add_stage7_add_cast = {Add_op_stage5[28:0], 3'b000};
  assign Add_stage7_add_cast_1 = {{2{Gain5_out1[29]}}, Gain5_out1};
  assign Add_stage7_add_temp = Add_stage7_add_cast + Add_stage7_add_cast_1;
  assign Add_op_stage6 = {{3{Add_stage7_add_temp[31]}}, Add_stage7_add_temp};



  assign Gain6_out1 = {{2{x7[1]}}, x7};


  assign Add_stage8_add_cast = Add_op_stage6[31:0];
  assign Add_stage8_add_cast_1 = {{8{Gain6_out1[3]}}, {Gain6_out1, 20'b00000000000000000000}};
  assign Add_stage8_add_temp = Add_stage8_add_cast + Add_stage8_add_cast_1;
  assign Add_out1 = Add_stage8_add_temp[26:11];


  assign ypred = Add_out1;

endmodule  // ML_Regression

