// -------------------------------------------------------------
// 
// File Name: hdlsrc\DNN_Simulation_Model\BinaryPrediction.v
// Created: 2024-08-06 14:40:13
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BinaryPrediction
// Source Path: DNN_Simulation_Model/DNN_Subsystem/BinaryPrediction
// Hierarchy Level: 1
// Model version: 1.24
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BinaryPrediction
          (u,
           Thresh,
           yprd);


  input   signed [15:0] u;  // sfix16_En14
  input   Thresh;  // ufix1_En1
  output  yprd;  // ufix1


  reg  yprd_1;  // ufix1
  reg signed [15:0] cast;  // sfix16_En14


  always @(Thresh, u) begin
    //MATLAB Function 'DNN_Subsystem/BinaryPrediction'
    cast = {2'b0, {Thresh, 13'b0000000000000}};
    if (u > cast) begin
      yprd_1 = 1'b1;
    end
    else begin
      yprd_1 = 1'b0;
    end
  end


  assign yprd = yprd_1;

endmodule  // BinaryPrediction

