// -------------------------------------------------------------
// 
// File Name: hdlsrc\DNN_Simulation_Model\Hidden_Layer2.v
// Created: 2024-08-06 14:40:13
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Hidden_Layer2
// Source Path: DNN_Simulation_Model/DNN_Subsystem/Hidden_Layer2
// Hierarchy Level: 1
// Model version: 1.24
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Hidden_Layer2
          (Bias_0,
           Bias_1,
           Bias_2,
           Bias_3,
           Weight_0,
           Weight_1,
           Weight_2,
           Weight_3,
           Weight_4,
           Weight_5,
           Weight_6,
           Weight_7,
           Weight_8,
           Weight_9,
           Weight_10,
           Weight_11,
           X_0,
           X_1,
           X_2,
           ytan_0,
           ytan_1,
           ytan_2,
           ytan_3);


  input   signed [4:0] Bias_0;  // sfix5_En2
  input   signed [4:0] Bias_1;  // sfix5_En2
  input   signed [4:0] Bias_2;  // sfix5_En2
  input   signed [4:0] Bias_3;  // sfix5_En2
  input   signed [4:0] Weight_0;  // sfix5_En2
  input   signed [4:0] Weight_1;  // sfix5_En2
  input   signed [4:0] Weight_2;  // sfix5_En2
  input   signed [4:0] Weight_3;  // sfix5_En2
  input   signed [4:0] Weight_4;  // sfix5_En2
  input   signed [4:0] Weight_5;  // sfix5_En2
  input   signed [4:0] Weight_6;  // sfix5_En2
  input   signed [4:0] Weight_7;  // sfix5_En2
  input   signed [4:0] Weight_8;  // sfix5_En2
  input   signed [4:0] Weight_9;  // sfix5_En2
  input   signed [4:0] Weight_10;  // sfix5_En2
  input   signed [4:0] Weight_11;  // sfix5_En2
  input   signed [15:0] X_0;  // sfix16_En14
  input   signed [15:0] X_1;  // sfix16_En14
  input   signed [15:0] X_2;  // sfix16_En14
  output  signed [15:0] ytan_0;  // sfix16_En14
  output  signed [15:0] ytan_1;  // sfix16_En14
  output  signed [15:0] ytan_2;  // sfix16_En14
  output  signed [15:0] ytan_3;  // sfix16_En14


  wire signed [4:0] Bias [0:3];  // sfix5_En2 [4]
  wire signed [4:0] Weight [0:3] [0:2];  // sfix5_En2 [4x3]
  wire signed [15:0] X [0:2];  // sfix16_En14 [3]
  reg signed [15:0] ytan [0:3];  // sfix16_En14 [4]
  reg signed [15:0] y;  // sfix16_En10
  reg signed [31:0] k;  // int32
  reg signed [20:0] prodAB;  // sfix21_En16
  reg signed [22:0] c;  // sfix23_En16
  reg signed [31:0] k_0;  // int32
  reg signed [15:0] slice_temp;  // sfix16_En10
  reg signed [15:0] add_cast [0:3];  // sfix16_En10 [4]
  reg signed [16:0] add_cast_0 [0:3];  // sfix17_En10 [4]
  reg signed [16:0] add_cast_1 [0:3];  // sfix17_En10 [4]
  reg signed [16:0] add_temp [0:3];  // sfix17_En10 [4]
  reg signed [23:0] add_cast_2 [0:2];  // sfix24_En16 [3]
  reg signed [23:0] add_cast_3 [0:2];  // sfix24_En16 [3]
  reg signed [23:0] add_temp_0 [0:2];  // sfix24_En16 [3]
  reg signed [31:0] mul_temp [0:3];  // sfix32_En20 [4]
  reg signed [32:0] add_cast_4 [0:3];  // sfix33_En20 [4]
  reg signed [32:0] add_temp_1 [0:3];  // sfix33_En20 [4]
  reg signed [31:0] mul_temp_0 [0:3];  // sfix32_En20 [4]
  reg signed [31:0] mul_temp_1 [0:3];  // sfix32_En20 [4]
  reg signed [32:0] add_cast_5 [0:3];  // sfix33_En20 [4]
  reg signed [32:0] add_temp_2 [0:3];  // sfix33_En20 [4]


  assign Bias[0] = Bias_0;
  assign Bias[1] = Bias_1;
  assign Bias[2] = Bias_2;
  assign Bias[3] = Bias_3;

  assign Weight[0][0] = Weight_0;
  assign Weight[1][0] = Weight_1;
  assign Weight[2][0] = Weight_2;
  assign Weight[3][0] = Weight_3;
  assign Weight[0][1] = Weight_4;
  assign Weight[1][1] = Weight_5;
  assign Weight[2][1] = Weight_6;
  assign Weight[3][1] = Weight_7;
  assign Weight[0][2] = Weight_8;
  assign Weight[1][2] = Weight_9;
  assign Weight[2][2] = Weight_10;
  assign Weight[3][2] = Weight_11;

  assign X[0] = X_0;
  assign X[1] = X_1;
  assign X[2] = X_2;

  always @* begin
    c = 23'sb00000000000000000000000;
    y = 16'sb0000000000000000;
    prodAB = 21'sb000000000000000000000;
    slice_temp = 16'sb0000000000000000;
    //MATLAB Function 'DNN_Subsystem/Hidden_Layer2'

    for(k = 32'sd0; k <= 32'sd3; k = k + 32'sd1) begin
      c = 23'sb00000000000000000000000;

      for(k_0 = 32'sd0; k_0 <= 32'sd2; k_0 = k_0 + 32'sd1) begin
        prodAB = Weight[k][k_0] * X[k_0];
        add_cast_2[k_0] = {c[22], c};
        add_cast_3[k_0] = {{3{prodAB[20]}}, prodAB};
        add_temp_0[k_0] = add_cast_2[k_0] + add_cast_3[k_0];
        if ((add_temp_0[k_0][23] == 1'b0) && (add_temp_0[k_0][22] != 1'b0)) begin
          c = 23'sb01111111111111111111111;
        end
        else if ((add_temp_0[k_0][23] == 1'b1) && (add_temp_0[k_0][22] != 1'b1)) begin
          c = 23'sb10000000000000000000000;
        end
        else begin
          c = add_temp_0[k_0][22:0];
        end
      end

      if (((c[22] == 1'b0) && (c[21] != 1'b0)) || ((c[22] == 1'b0) && (c[21:6] == 16'sb0111111111111111))) begin
        add_cast[k] = 16'sb0111111111111111;
      end
      else if ((c[22] == 1'b1) && (c[21] != 1'b1)) begin
        add_cast[k] = 16'sb1000000000000000;
      end
      else begin
        add_cast[k] = c[21:6] + $signed({1'b0, c[5]});
      end
      add_cast_0[k] = {add_cast[k][15], add_cast[k]};
      add_cast_1[k] = {{4{Bias[k][4]}}, {Bias[k], 8'b00000000}};
      add_temp[k] = add_cast_0[k] + add_cast_1[k];
      if ((add_temp[k][16] == 1'b0) && (add_temp[k][15] != 1'b0)) begin
        slice_temp = 16'sb0111111111111111;
      end
      else if ((add_temp[k][16] == 1'b1) && (add_temp[k][15] != 1'b1)) begin
        slice_temp = 16'sb1000000000000000;
      end
      else begin
        slice_temp = add_temp[k][15:0];
      end
      // Word Length
      // Fractional Length
      // Slopes and Offsets
      // Piecewise Linear Approximation of Tanh Function
      if (slice_temp < 16'sb1111100000000000) begin
        y = 16'sb1111110000000000;
      end
      else if (slice_temp < 16'sb1111101110011010) begin
        mul_temp[k] = 16'sb0000000010111000 * slice_temp;
        add_cast_4[k] = {mul_temp[k][31], mul_temp[k]};
        add_temp_1[k] = add_cast_4[k] + 33'sh1FFF47C00;
        y = add_temp_1[k][25:10];
      end
      else if ((slice_temp >= 16'sb1111101110011010) && (slice_temp <= 16'sb0000010001100110)) begin
        mul_temp_0[k] = 16'sb0000001101001000 * slice_temp;
        y = mul_temp_0[k][25:10];
      end
      else if (slice_temp <= 16'sb0000100000000000) begin
        mul_temp_1[k] = 16'sb0000000010111000 * slice_temp;
        add_cast_5[k] = {mul_temp_1[k][31], mul_temp_1[k]};
        add_temp_2[k] = add_cast_5[k] + 33'sh0000B8400;
        y = add_temp_2[k][25:10];
      end
      else begin
        y = 16'sb0000010000000000;
      end
      if ((y[15] == 1'b0) && (y[14:11] != 4'b0000)) begin
        ytan[k] = 16'sb0111111111111111;
      end
      else if ((y[15] == 1'b1) && (y[14:11] != 4'b1111)) begin
        ytan[k] = 16'sb1000000000000000;
      end
      else begin
        ytan[k] = {y[11:0], 4'b0000};
      end
    end

  end


  assign ytan_0 = ytan[0];

  assign ytan_1 = ytan[1];

  assign ytan_2 = ytan[2];

  assign ytan_3 = ytan[3];

endmodule  // Hidden_Layer2

