// -------------------------------------------------------------
// 
// File Name: hdlsrc\DNN_Simulation_Model\Hidden_Layer1.v
// Created: 2024-08-06 14:40:13
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Hidden_Layer1
// Source Path: DNN_Simulation_Model/DNN_Subsystem/Hidden_Layer1
// Hierarchy Level: 1
// Model version: 1.24
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Hidden_Layer1
          (Bias_0,
           Bias_1,
           Bias_2,
           Weight_0,
           Weight_1,
           Weight_2,
           Weight_3,
           Weight_4,
           Weight_5,
           Weight_6,
           Weight_7,
           Weight_8,
           Weight_9,
           Weight_10,
           Weight_11,
           Weight_12,
           Weight_13,
           Weight_14,
           Weight_15,
           Weight_16,
           Weight_17,
           Weight_18,
           Weight_19,
           Weight_20,
           Weight_21,
           Weight_22,
           Weight_23,
           X_0,
           X_1,
           X_2,
           X_3,
           X_4,
           X_5,
           X_6,
           X_7,
           ytan_0,
           ytan_1,
           ytan_2);


  input   signed [4:0] Bias_0;  // sfix5_En2
  input   signed [4:0] Bias_1;  // sfix5_En2
  input   signed [4:0] Bias_2;  // sfix5_En2
  input   signed [4:0] Weight_0;  // sfix5_En2
  input   signed [4:0] Weight_1;  // sfix5_En2
  input   signed [4:0] Weight_2;  // sfix5_En2
  input   signed [4:0] Weight_3;  // sfix5_En2
  input   signed [4:0] Weight_4;  // sfix5_En2
  input   signed [4:0] Weight_5;  // sfix5_En2
  input   signed [4:0] Weight_6;  // sfix5_En2
  input   signed [4:0] Weight_7;  // sfix5_En2
  input   signed [4:0] Weight_8;  // sfix5_En2
  input   signed [4:0] Weight_9;  // sfix5_En2
  input   signed [4:0] Weight_10;  // sfix5_En2
  input   signed [4:0] Weight_11;  // sfix5_En2
  input   signed [4:0] Weight_12;  // sfix5_En2
  input   signed [4:0] Weight_13;  // sfix5_En2
  input   signed [4:0] Weight_14;  // sfix5_En2
  input   signed [4:0] Weight_15;  // sfix5_En2
  input   signed [4:0] Weight_16;  // sfix5_En2
  input   signed [4:0] Weight_17;  // sfix5_En2
  input   signed [4:0] Weight_18;  // sfix5_En2
  input   signed [4:0] Weight_19;  // sfix5_En2
  input   signed [4:0] Weight_20;  // sfix5_En2
  input   signed [4:0] Weight_21;  // sfix5_En2
  input   signed [4:0] Weight_22;  // sfix5_En2
  input   signed [4:0] Weight_23;  // sfix5_En2
  input   signed [11:0] X_0;  // sfix12_En11
  input   signed [11:0] X_1;  // sfix12_En11
  input   signed [11:0] X_2;  // sfix12_En11
  input   signed [11:0] X_3;  // sfix12_En11
  input   signed [11:0] X_4;  // sfix12_En11
  input   signed [11:0] X_5;  // sfix12_En11
  input   signed [11:0] X_6;  // sfix12_En11
  input   signed [11:0] X_7;  // sfix12_En11
  output  signed [15:0] ytan_0;  // sfix16_En14
  output  signed [15:0] ytan_1;  // sfix16_En14
  output  signed [15:0] ytan_2;  // sfix16_En14


  wire signed [4:0] Bias [0:2];  // sfix5_En2 [3]
  wire signed [4:0] Weight [0:2] [0:7];  // sfix5_En2 [3x8]
  wire signed [11:0] X [0:7];  // sfix12_En11 [8]
  reg signed [15:0] ytan [0:2];  // sfix16_En14 [3]
  reg signed [15:0] y;  // sfix16_En10
  reg signed [31:0] k;  // int32
  reg signed [16:0] prodAB;  // sfix17_En13
  reg signed [19:0] c;  // sfix20_En13
  reg signed [31:0] k_0;  // int32
  reg signed [15:0] slice_temp;  // sfix16_En10
  reg signed [15:0] add_cast [0:2];  // sfix16_En10 [3]
  reg signed [16:0] add_cast_0 [0:2];  // sfix17_En10 [3]
  reg signed [16:0] add_cast_1 [0:2];  // sfix17_En10 [3]
  reg signed [16:0] add_temp [0:2];  // sfix17_En10 [3]
  reg signed [20:0] add_cast_2 [0:7];  // sfix21_En13 [8]
  reg signed [20:0] add_cast_3 [0:7];  // sfix21_En13 [8]
  reg signed [20:0] add_temp_0 [0:7];  // sfix21_En13 [8]
  reg signed [31:0] mul_temp [0:2];  // sfix32_En20 [3]
  reg signed [32:0] add_cast_4 [0:2];  // sfix33_En20 [3]
  reg signed [32:0] add_temp_1 [0:2];  // sfix33_En20 [3]
  reg signed [31:0] mul_temp_0 [0:2];  // sfix32_En20 [3]
  reg signed [31:0] mul_temp_1 [0:2];  // sfix32_En20 [3]
  reg signed [32:0] add_cast_5 [0:2];  // sfix33_En20 [3]
  reg signed [32:0] add_temp_2 [0:2];  // sfix33_En20 [3]


  assign Bias[0] = Bias_0;
  assign Bias[1] = Bias_1;
  assign Bias[2] = Bias_2;

  assign Weight[0][0] = Weight_0;
  assign Weight[1][0] = Weight_1;
  assign Weight[2][0] = Weight_2;
  assign Weight[0][1] = Weight_3;
  assign Weight[1][1] = Weight_4;
  assign Weight[2][1] = Weight_5;
  assign Weight[0][2] = Weight_6;
  assign Weight[1][2] = Weight_7;
  assign Weight[2][2] = Weight_8;
  assign Weight[0][3] = Weight_9;
  assign Weight[1][3] = Weight_10;
  assign Weight[2][3] = Weight_11;
  assign Weight[0][4] = Weight_12;
  assign Weight[1][4] = Weight_13;
  assign Weight[2][4] = Weight_14;
  assign Weight[0][5] = Weight_15;
  assign Weight[1][5] = Weight_16;
  assign Weight[2][5] = Weight_17;
  assign Weight[0][6] = Weight_18;
  assign Weight[1][6] = Weight_19;
  assign Weight[2][6] = Weight_20;
  assign Weight[0][7] = Weight_21;
  assign Weight[1][7] = Weight_22;
  assign Weight[2][7] = Weight_23;

  assign X[0] = X_0;
  assign X[1] = X_1;
  assign X[2] = X_2;
  assign X[3] = X_3;
  assign X[4] = X_4;
  assign X[5] = X_5;
  assign X[6] = X_6;
  assign X[7] = X_7;

  always @* begin
    c = 20'sb00000000000000000000;
    y = 16'sb0000000000000000;
    prodAB = 17'sb00000000000000000;
    slice_temp = 16'sb0000000000000000;
    //MATLAB Function 'DNN_Subsystem/Hidden_Layer1'

    for(k = 32'sd0; k <= 32'sd2; k = k + 32'sd1) begin
      c = 20'sb00000000000000000000;

      for(k_0 = 32'sd0; k_0 <= 32'sd7; k_0 = k_0 + 32'sd1) begin
        prodAB = Weight[k][k_0] * X[k_0];
        add_cast_2[k_0] = {c[19], c};
        add_cast_3[k_0] = {{4{prodAB[16]}}, prodAB};
        add_temp_0[k_0] = add_cast_2[k_0] + add_cast_3[k_0];
        if ((add_temp_0[k_0][20] == 1'b0) && (add_temp_0[k_0][19] != 1'b0)) begin
          c = 20'sb01111111111111111111;
        end
        else if ((add_temp_0[k_0][20] == 1'b1) && (add_temp_0[k_0][19] != 1'b1)) begin
          c = 20'sb10000000000000000000;
        end
        else begin
          c = add_temp_0[k_0][19:0];
        end
      end

      if (((c[19] == 1'b0) && (c[18] != 1'b0)) || ((c[19] == 1'b0) && (c[18:3] == 16'sb0111111111111111))) begin
        add_cast[k] = 16'sb0111111111111111;
      end
      else if ((c[19] == 1'b1) && (c[18] != 1'b1)) begin
        add_cast[k] = 16'sb1000000000000000;
      end
      else begin
        add_cast[k] = c[18:3] + $signed({1'b0, c[2]});
      end
      add_cast_0[k] = {add_cast[k][15], add_cast[k]};
      add_cast_1[k] = {{4{Bias[k][4]}}, {Bias[k], 8'b00000000}};
      add_temp[k] = add_cast_0[k] + add_cast_1[k];
      if ((add_temp[k][16] == 1'b0) && (add_temp[k][15] != 1'b0)) begin
        slice_temp = 16'sb0111111111111111;
      end
      else if ((add_temp[k][16] == 1'b1) && (add_temp[k][15] != 1'b1)) begin
        slice_temp = 16'sb1000000000000000;
      end
      else begin
        slice_temp = add_temp[k][15:0];
      end
      // Word Length
      // Fractional Length
      // Slopes and Offsets
      // Piecewise Linear Approximation of Tanh Function
      if (slice_temp < 16'sb1111100000000000) begin
        y = 16'sb1111110000000000;
      end
      else if (slice_temp < 16'sb1111101110011010) begin
        mul_temp[k] = 16'sb0000000010111000 * slice_temp;
        add_cast_4[k] = {mul_temp[k][31], mul_temp[k]};
        add_temp_1[k] = add_cast_4[k] + 33'sh1FFF47C00;
        y = add_temp_1[k][25:10];
      end
      else if ((slice_temp >= 16'sb1111101110011010) && (slice_temp <= 16'sb0000010001100110)) begin
        mul_temp_0[k] = 16'sb0000001101001000 * slice_temp;
        y = mul_temp_0[k][25:10];
      end
      else if (slice_temp <= 16'sb0000100000000000) begin
        mul_temp_1[k] = 16'sb0000000010111000 * slice_temp;
        add_cast_5[k] = {mul_temp_1[k][31], mul_temp_1[k]};
        add_temp_2[k] = add_cast_5[k] + 33'sh0000B8400;
        y = add_temp_2[k][25:10];
      end
      else begin
        y = 16'sb0000010000000000;
      end
      if ((y[15] == 1'b0) && (y[14:11] != 4'b0000)) begin
        ytan[k] = 16'sb0111111111111111;
      end
      else if ((y[15] == 1'b1) && (y[14:11] != 4'b1111)) begin
        ytan[k] = 16'sb1000000000000000;
      end
      else begin
        ytan[k] = {y[11:0], 4'b0000};
      end
    end

  end


  assign ytan_0 = ytan[0];

  assign ytan_1 = ytan[1];

  assign ytan_2 = ytan[2];

endmodule  // Hidden_Layer1

